import 'dotenv/config';

function opt(key, fallback) {
  return process.env[key] ?? fallback;
}

function num(key, fallback) {
  const value = process.env[key];
  return value !== undefined && value !== '' ? Number(value) : fallback;
}

function bool(key, fallback) {
  const value = process.env[key];
  if (value === undefined || value === '') return fallback;
  return /^(1|true|yes|on)$/i.test(value);
}

function csv(key, fallback) {
  return opt(key, fallback)
    .split(',')
    .map((item) => item.trim().toLowerCase())
    .filter(Boolean);
}

export const VALUE_DRY_RUN = bool('VALUE_DRY_RUN', true);
export const VALUE_POLL_MS = num('VALUE_POLL_MS', 1_000);
export const VALUE_MARKET_REFRESH_MS = num('VALUE_MARKET_REFRESH_MS', 15_000);
export const VALUE_SYMBOLS = csv('VALUE_SYMBOLS', 'btc,eth,sol,xrp');
export const VALUE_DURATIONS = csv('VALUE_DURATIONS', '5m,15m');
export const VALUE_TARGET_PRICE = num('VALUE_TARGET_PRICE', 0.40);
export const VALUE_ABSOLUTE_FIRST_LEG_MAX_PRICE = num('VALUE_ABSOLUTE_FIRST_LEG_MAX_PRICE', 0.45);
export const VALUE_MAX_SLIPPAGE = num('VALUE_MAX_SLIPPAGE', 0.03);
export const VALUE_ORDER_MODE = opt('VALUE_ORDER_MODE', 'USDC').toUpperCase();
export const VALUE_LEG_USDC = num('VALUE_LEG_USDC', 1);
export const VALUE_TARGET_SHARES = num('VALUE_TARGET_SHARES', 5);
export const VALUE_OPEN_WAIT_SECONDS = num('VALUE_OPEN_WAIT_SECONDS', 20);
export const VALUE_STABLE_SNAPSHOTS_REQUIRED = num('VALUE_STABLE_SNAPSHOTS_REQUIRED', 3);
export const VALUE_MAX_SPREAD = num('VALUE_MAX_SPREAD', 0.05);
export const VALUE_EXTREME_SPREAD = num('VALUE_EXTREME_SPREAD', 0.10);
export const VALUE_REQUIRED_DEPTH_MULTIPLIER = num('VALUE_REQUIRED_DEPTH_MULTIPLIER', 2);
export const VALUE_FIRST_LEG_CUTOFF_SECONDS = num('VALUE_FIRST_LEG_CUTOFF_SECONDS', 60);
export const VALUE_SECOND_LEG_CUTOFF_SECONDS = num('VALUE_SECOND_LEG_CUTOFF_SECONDS', 15);
export const VALUE_SECOND_LEG_MIN_LOCK_PROFIT_PER_SHARE = num('VALUE_SECOND_LEG_MIN_LOCK_PROFIT_PER_SHARE', 0.04);
export const VALUE_SECOND_LEG_HARD_MAX_PRICE = num('VALUE_SECOND_LEG_HARD_MAX_PRICE', 0.46);
export const VALUE_SECOND_LEG_MAX_SPREAD = num('VALUE_SECOND_LEG_MAX_SPREAD', 0.06);
export const VALUE_SECOND_LEG_EXTREME_SPREAD = num('VALUE_SECOND_LEG_EXTREME_SPREAD', 0.12);
export const VALUE_SECOND_LEG_MIN_DEPTH_MULTIPLIER = num('VALUE_SECOND_LEG_MIN_DEPTH_MULTIPLIER', 1);
export const VALUE_MAX_ONE_LEG_HOLD_MS_5M = num('VALUE_MAX_ONE_LEG_HOLD_MS_5M', 90_000);
export const VALUE_MAX_ONE_LEG_HOLD_MS_15M = num('VALUE_MAX_ONE_LEG_HOLD_MS_15M', 300_000);
export const VALUE_EXTENDED_HOLD_MAX_MS_5M = num('VALUE_EXTENDED_HOLD_MAX_MS_5M', 45_000);
export const VALUE_EXTENDED_HOLD_MAX_MS_15M = num('VALUE_EXTENDED_HOLD_MAX_MS_15M', 180_000);
export const VALUE_FINAL_EXIT_BEFORE_EXPIRY_MS_5M = num('VALUE_FINAL_EXIT_BEFORE_EXPIRY_MS_5M', 45_000);
export const VALUE_FINAL_EXIT_BEFORE_EXPIRY_MS_15M = num('VALUE_FINAL_EXIT_BEFORE_EXPIRY_MS_15M', 180_000);
export const VALUE_CONTINUE_MIN_PROFIT_PER_SHARE = num('VALUE_CONTINUE_MIN_PROFIT_PER_SHARE', 0.005);
export const VALUE_DIRECT_TAKE_PROFIT_PER_SHARE = num('VALUE_DIRECT_TAKE_PROFIT_PER_SHARE', 0.03);
export const VALUE_TRAILING_DRAWDOWN_PER_SHARE_5M = num('VALUE_TRAILING_DRAWDOWN_PER_SHARE_5M', 0.025);
export const VALUE_TRAILING_DRAWDOWN_PER_SHARE_15M = num('VALUE_TRAILING_DRAWDOWN_PER_SHARE_15M', 0.035);
export const VALUE_NO_UNPAIRED_HOLD_LAST_MS_5M = num('VALUE_NO_UNPAIRED_HOLD_LAST_MS_5M', 60_000);
export const VALUE_NO_UNPAIRED_HOLD_LAST_MS_15M = num('VALUE_NO_UNPAIRED_HOLD_LAST_MS_15M', 180_000);
export const VALUE_MAX_BOOK_AGE_MS = num('VALUE_MAX_BOOK_AGE_MS', 1_500);
export const VALUE_MAX_UNPAIRED_LOSS_PER_SHARE = num('VALUE_MAX_UNPAIRED_LOSS_PER_SHARE', 0.10);
export const VALUE_MERGE_ON_SECOND_LEG = bool('VALUE_MERGE_ON_SECOND_LEG', true);
export const VALUE_IMMEDIATE_EXIT_BELOW_PRICE = num('VALUE_IMMEDIATE_EXIT_BELOW_PRICE', 0);
export const VALUE_ENDGAME_EXIT_BELOW_PRICE = num('VALUE_ENDGAME_EXIT_BELOW_PRICE', 0.10);
export const VALUE_MAX_OPEN_MARKETS = num('VALUE_MAX_OPEN_MARKETS', 20);
export const VALUE_MAX_STRANDED_LEGS = num('VALUE_MAX_STRANDED_LEGS', 10);
export const VALUE_DASHBOARD_ENABLED = bool('VALUE_DASHBOARD_ENABLED', true);
export const VALUE_DASHBOARD_HOST = opt('VALUE_DASHBOARD_HOST', '127.0.0.1');
export const VALUE_DASHBOARD_PORT = num('VALUE_DASHBOARD_PORT', 8797);
